import java.io.*;
public class Airways
{
public void airtravels()throws IOException
 {
     
InputStreamReader ir=new InputStreamReader(System.in);
BufferedReader br=new BufferedReader(ir);
int trip,dest,amd=0,snum,start=0,cart;
String name,sur,add,p1,m1,date,choice;
do
{
System.out.println("Jet Airways"); 
System.out.println("Enter the following details for your trip"); //Starts the detail acception System.out.println("$$$$$$$$$$ Welcome to Online Booking of Jet Airways $$$$$$$$$$");
System.out.println("Enter the Details to book tickets");
System.out.println("From:");
System.out.println("1.Ahmedabad Term IA");
System.out.println("2.Bhopal");
System.out.println("3.Chandigarh");
System.out.println("4.Delhi");
System.out.println("5.Mumbai Term IB");
System.out.println("6.Coimbatore");
start=Integer.parseInt(br.readLine()); //details for destination if(start==1) { System.out.println("To:"); System.out.println("1.Bhopal");
if(start==1) { System.out.println("To:"); System.out.println("1.Bhopal");
System.out.println("2.Chandigarh");
System.out.println("3.Delhi");
System.out.println("4.Mumbai Term IB");
System.out.println("5.Coimbatore");
amd=Integer.parseInt(br.readLine()); 
if(amd==1)//Ahmedabad to Bhopal 
{
 System.out.println("Departure: Ahmedabad Term IA"); 
 System.out.println("Arrival: Bhopal");
System.out.println("Departure Time: 6.00 hrs");
System.out.println("Arrival: 7.30 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.4250");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.5800");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=5800*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4001");
System.out.println("Departure: Ahmedabad");
System.out.println("Arrival: Bhopal");
System.out.println("Departure Time: 6.00AM");
System.out.println("Arrival Time: 7.30AM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==2) //Ahmedabad to Chandigarh
{
System.out.println("Departure: Ahmedabad Term IA"); System.out.println("Arrival: Chandigarh");
System.out.println("Departure Time: 4.30 hrs");
System.out.println("Arrival: 6.30 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.5100");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.6650");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=6650*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4002");
System.out.println("Departure: Ahmedabad");
System.out.println("Arrival: Chandigarh");
System.out.println("Departure Time: 4.30AM");
System.out.println("Arrival Time: 6.30AM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==3)
{ //Ahmedabad to Delhi 
 System.out.println("Departure: Ahmedabad Term IA"); 
 System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 8.30 hrs");
System.out.println("Arrival: 10.00 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.5000");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.6550");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=6550*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4003");
System.out.println("Departure: Ahmedabad");
System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 8.30AM");
System.out.println("Arrival Time: 10.00AM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==4)
{ //Ahmedabad to Mumbai Term IB
System.out.println("Departure: Ahmedabad Term IA"); 
System.out.println("Arrival: Mumbai Term IB");
System.out.println("Departure Time: 12.30 hrs");
System.out.println("Arrival: 13.15 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.1500");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.3050");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=3050*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4004");
System.out.println("Departure: Ahmedabad");
System.out.println("Arrival: Mumbai Term IB");
System.out.println("Departure Time: 12.30PM");
System.out.println("Arrival Time: 13.15PM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==5)
{ //Ahmedabad to Coimbatore
 System.out.println("Departure: Ahmedabad Term IA"); 
 System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 8.30 hrs");
System.out.println("Arrival: 10.30 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.3500");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.5050");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: TheExamPapers.com ");
snum=Integer.parseInt(br.readLine());
cart=5050*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4005");
System.out.println("Departure: Ahmedabad");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 8.30AM");
System.out.println("Arrival Time: 10.30AM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else
{
 System.out.println("The choice entered is invalid"); 
}
}//end of Ahmedabad Departure 
else if(start==2) //Departure Bhopal 
{
System.out.println("To:");
System.out.println("1.Ahmedabad Term IA");
System.out.println("2.Chandigarh");
System.out.println("3.Delhi");
System.out.println("4.Mumbai Term IB");
System.out.println("5.Coimbatore");
amd=Integer.parseInt(br.readLine());
if(amd==1)
{ //Bhopal to Ahmedabad 
System.out.println("Departure: Bhopal"); 
System.out.println("Arrival: Ahmedabad Term IA");
 System.out.println("Departure Time: 7.30 hrs");
System.out.println("Arrival: 9.00 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.4250");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.5800");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=5800*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4001");
System.out.println("Departure: Bhopal");
System.out.println("Arrival: Ahmedabad Term IA"); System.out.println("Departure Time: 7.30AM");
System.out.println("Arrival Time: 9.00AM TheExamPapers.com");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==2)
{ //Bhopal to Chandigarh 
System.out.println("Departure: Bhopal");
System.out.println("Arrival: Chandigarh");
System.out.println("Departure Time: 17.30 hrs");
System.out.println("Arrival: 18.45 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.3300");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.4850");

System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=2550*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4007");
System.out.println("Departure: Bhopal");
System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 10.00PM");
System.out.println("Arrival Time: 10.45PM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==4)
{ //Bhopal to Mumbai Term IA
 System.out.println("Departure: Bhopal");
System.out.println("Arrival: Mumbai");
System.out.println("Departure Time: 0200 hrs");
System.out.println("Arrival: 0315 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.2500");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.4050");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=4050*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4008");
System.out.println("Departure: Bhopal");
System.out.println("Arrival: Mumbai");
System.out.println("Departure Time: 02.00AM");
System.out.println("Arrival Time: 03.15AM");
System.out.println("Seat No. will be given at the time of Security Check");
}else if(amd==5)
{ //Bhopal to Coimbatore 
 System.out.println("Departure: Bhopal");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 1630 hrs");
System.out.println("Arrival: 1830 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.6500");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.8050");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=8050*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4009");
System.out.println("Departure: Bhopal");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 4.30 PM");
System.out.println("Arrival Time: 6.30 PM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else
{
 System.out.println("The choice entered is invalid"); 
}
}//end of Bhopal Departure 
 else if(start==3) 
 {
System.out.println("To: ");
System.out.println("1.Ahmedabad Term IA");
System.out.println("2.Bhopal");
System.out.println("3.Delhi");
System.out.println("4.Mumbai Term IB");
System.out.println("5.Coimbatore");
amd=Integer.parseInt(br.readLine());
if(amd==1)//Chandi to Ahmedabad 
{ 
System.out.println("Departure: Chandigarh"); 
System.out.println("Arrival: Ahmedabad Term IA"); 
System.out.println("Departure Time: 1845 hrs");
System.out.println("Arrival: 2045 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.5100");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.6650");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=6650*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4002");
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Ahmedabad Term IA"); 
System.out.println("Departure Time: 6.30 PM"); 
System.out.println("Arrival Time: 8.30 PM"); 
System.out.println("Seat No. will be given at the time of Security Check"); 
}

else if(amd==2)
{ //Chandigarh to Bhopal 
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Bhopal");
System.out.println("Departure Time: 1845 hrs");
System.out.println("Arrival: 2015 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.3300");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.4850");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=4850*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4006");
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Bhopal");
System.out.println("Departure Time: 6.45 PM");
System.out.println("Arrival Time: 8.15 PM"); 
System.out.println("Seat No. will be given at the time of Security Check"); 
}
else if(amd==3)// Chandigarh to Delhi
{
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 1500 hrs");
System.out.println("Arrival: 1600 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.2200");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.3750");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=3750*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4010");
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 3.00 PM");
System.out.println("Arrival Time: 4.00 PM"); 
System.out.println("Seat No. will be given at the time of Security Check"); 
}
else if(amd==4)//Chandigarh to Mumbai 
{
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Mumbai");
System.out.println("Departure Time: 1430 hrs");
System.out.println("Arrival: 1600 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.3200");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.4750");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=4750*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4011");
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Mumbai Term IB");
System.out.println("Departure Time: 2.30 PM");
System.out.println("Arrival Time: 4.00 PM"); 
System.out.println("Seat No. will be given at the time of Security Check"); 
}
else if(amd==5) //Chandigarh to Coimbatore 
{
 System.out.println("Departure: Chandigarh");
 System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 1230 hrs");
System.out.println("Arrival: 1500 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.7200");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.8750");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=8750*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4012");
System.out.println("Departure: Chandigarh");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 12.30 PM");
System.out.println("Arrival Time: 3.00 PM");
 System.out.println("Seat No. will be given at the time of Security Check"); 
}
else 
System.out.println("The choice entered is invalid");
}//end of Chandigarh Depart
else if(start==4)//Delhi Departure
{
System.out.println("To: ");
System.out.println("1.Ahmedabad Term IA");
System.out.println("2.Bhopal");
System.out.println("3.Chandigarh");
System.out.println("4.Mumbai Term IB");
System.out.println("5.Coimbatore");
amd=Integer.parseInt(br.readLine());
if(amd==1)//Delhi to Ahmedabad 
{ 
System.out.println("Departure: Delhi"); 
System.out.println("Arrival: Ahmedabad Term IA"); 
System.out.println("Departure Time: 1000 hrs");
System.out.println("Arrival: 1130 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.5000");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.6550");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=6550*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4003");
System.out.println("Departure: Delhi");
System.out.println("Arrival: Ahmedabad Term IA"); System.out.println("Departure Time: 10.00AM");
System.out.println("Arrival Time: 11.30AM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==2)//Delhi to Bhopal 
{
 System.out.println("Departure: Delhi");
System.out.println("Arrival: Bhopal");
System.out.println("Departure Time: 2300 hrs");
System.out.println("Arrival: 2345 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.1000");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.2550");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=2550*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4007");
System.out.println("Departure: Delhi");
System.out.println("Arrival: Bhopal");
System.out.println("Departure Time: 11.00PM");
System.out.println("Arrival Time: 11.45PM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==3)//Delhi to Chandigarh 
{
System.out.println("Departure: Delhi");
System.out.println("Arrival: Chandigarh");
System.out.println("Departure Time: 1630 hrs");
System.out.println("Arrival: 1730 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.2200");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.3750");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=3750*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);

System.out.println("Departure: Delhi");
System.out.println("Arrival: Mumbai Term IB");
System.out.println("Departure Time: 11.00 AM");
System.out.println("Arrival Time: 01.00 PM");
 System.out.println("Seat No. will be given at the time of Security Check"); 
}
else if(amd==5)//Delhi to Coimbatore 
{
System.out.println("Departure: Delhi");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 1630 hrs");
System.out.println("Arrival: 1930 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.7800");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.9350");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=9350*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4014");
System.out.println("Departure: Delhi");
System.out.println("Arrival: Coimbatore"); 
System.out.println("Departure Time: 4.30 PM"); 
System.out.println("Arrival Time: 7.30 PM");
 System.out.println("Seat No. will be given at the time of Security Check");
}
else System.out.println("The choice entered is invalid");
}//end of Delhi Depart
else if(start==5)// Mumbai Depart
{
System.out.println("To: ");
System.out.println("1.Ahmedabad Term IA");
System.out.println("2.Bhopal");
System.out.println("3.Chandigarh");
System.out.println("4.Delhi");
System.out.println("5.Coimbatore");
amd=Integer.parseInt(br.readLine());
if(amd==1)//Mumbai to Ahmedabad 
{ 
System.out.println("Departure: Mumbai Term IB");
 System.out.println("Arrival: Ahmedabad Term IA");
 System.out.println("Departure Time: 13.30 hrs");
System.out.println("Arrival: 14.15 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.1500");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.3050");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=3050*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4004");
System.out.println("Departure: Mumbai Term IB");
System.out.println("Arrival: Ahmedabad Term IA"); System.out.println("Departure Time: 01.30 PM");
System.out.println("Arrival Time: 02.15PM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==2)//Mumbai to Bhopal 
{
System.out.println("Departure: Mumbai");
System.out.println("Arrival: Bhopa");
System.out.println("Departure Time: 0330 hrs");
System.out.println("Arrival: 0415 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.2500");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.4050");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=4050*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");

System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4011");
System.out.println("Departure: Mumbai Term IB");
System.out.println("Arrival: Chandigarh");
System.out.println("Departure Time: 4.15 PM");
System.out.println("Arrival Time: 5.45 PM"); 
System.out.println("Seat No. will be given at the time of Security Check");
 }
 else if(amd==4)//Mumbai to Delhi 
 {
System.out.println("Departure: Mumbai");
System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 1330 hrs");
System.out.println("Arrival: 1530 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.5800");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.7350");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=7350*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4013");
System.out.println("Departure: Mumbai");
System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 01.30 PM");
System.out.println("Arrival Time: 03.30 PM"); System.out.println("Seat No. will be given at the time of Security Check"); 
}else if(amd==5)//Mumbai to Coimbatore
 { 
     System.out.println("Departure: Mumbai");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 0700 hrs");
System.out.println("Arrival: 0900 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.6100");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.7650");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=7650*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4015");
System.out.println("Departure: Mumbai");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 07.00 AM"); 
System.out.println("Arrival Time: 09.00 AM"); 
System.out.println("Seat No. will be given at the time of Security Check");
 }
 else System.out.println("The choice entered is invalid");
}//end of Mumbai Depart
else if(start==6)
{
System.out.println("To: ");
System.out.println("1.Ahmedabad Term IA");
System.out.println("2.Bhopal");
System.out.println("3.Chandigarh");
System.out.println("4.Delhi");
System.out.println("5.Mumbai");
amd=Integer.parseInt(br.readLine());
if(amd==1)//Coimb to Ahmed
 { 
     System.out.println("Departure: Coimbatore"); 
     System.out.println("Arrival: Ahmedabad Term IA"); 
     System.out.println("Departure Time: 1045 hrs");
System.out.println("Arrival: 1245 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.3500");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.5050");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();

System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=8050*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4009");
System.out.println("Departure: Coimbatore");
System.out.println("Arrival: Bhopal");
System.out.println("Departure Time: 6.45 PM");
System.out.println("Arrival Time: 8.45 PM");
System.out.println("Seat No. will be given at the time of Security Check");
}
else if(amd==3)//Coim to Chandigarh
 {
System.out.println("Departure: Coimbatore");
System.out.println("Arrival: Chandigarh");
System.out.println("Departure Time: 1530 hrs");
System.out.println("Arrival: 1900 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.7200");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.8750");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=8750*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4012");
System.out.println("Departure: Coimbatore");
System.out.println("Arrival: Chandigarh");
System.out.println("Departure Time: 03.30 PM");
System.out.println("Arrival Time: 07.00 PM"); 
System.out.println("Seat No. will be given at the time of Security Check");
 }
 else if(amd==4)//Coimb to Delhi
 {
System.out.println("Departure: Delhi");
System.out.println("Arrival: Coimbatore");
System.out.println("Departure Time: 2000 hrs");
System.out.println("Arrival: 2300 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.7800");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.9350");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=9350*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4014");
System.out.println("Departure: Coimatore");
System.out.println("Arrival: Delhi");
System.out.println("Departure Time: 8.00 PM");
System.out.println("Arrival Time: 11.00 PM"); 
System.out.println("Seat No. will be given at the time of Security Check");
 }
 else if(amd==5)//Coimb to Mumbai 
 { 
     System.out.println("Departure: Coimbatore");
System.out.println("Arrival: Mumbai");
System.out.println("Departure Time: 0930 hrs");
System.out.println("Arrival: 1130 hrs");
System.out.println("Price Details: ");
System.out.println("Fare Charges: Rs.6100");
System.out.println("Tax+Fuel Surcharges: Rs.1550");
System.out.println("Total price per ticket: Rs.7650");
System.out.println("Enter following details");
System.out.println("Name: ");
name=br.readLine();
System.out.println("Surname: ");
sur=br.readLine();
System.out.println("Address: ");
add=br.readLine();
System.out.println("Phone No.(Res): ");
p1=br.readLine();
System.out.println("Phone No.(Mobile): ");
m1=br.readLine();
System.out.println("Enter Date: ");
date=br.readLine();
System.out.println("Enter Number of Seats Required: ");
snum=Integer.parseInt(br.readLine());
cart=7650*snum;
System.out.println("Total price for "+snum+" tickets is Rs. "+cart);
System.out.println("Ticket details is as follows: \n");
System.out.println("********* Jet Airways The Ultimate Experience **********");
System.out.println("Name: "+name);
System.out.println("Surname: "+sur);
System.out.println("Address: "+add);
System.out.println("Contact Details: ");
System.out.println("Phone No.(Res): "+p1);
System.out.println("Phone No.(Mobile): "+m1);
System.out.println("Flight Details: \n");
System.out.println("Date: "+date);
System.out.println("Flight No. J4015");
System.out.println("Departure: Coimbatore");
System.out.println("Arrival: Mumbai");
System.out.println("Departure Time: 09.30 AM"); System.out.println("Arrival Time: 11.30 AM"); 
System.out.println("Seat No. will be given at the time of Security Check"); 
}
else 
System.out.println("The choice entered is invalid");
 }
 System.out.println("\n TICKETS ARE AVAILABLE AS PER SUBJECT TO AVAILABILITY. TICKET FARE IS STRICTLY NON-REFUNDABLE. WE ARE NOT RESPONSIBLE FOR DELAY OF FLIGHT DUE TO BAD WEATHER."); 
 System.out.println("PLEASE CARRY A PHOTO IDENTITY OF NAME BY WHICH THE TICKET/S ARE REGISTERED WHILE COLLECTING ORIGINAL COPY OF TICKET AT AIRPORT."); 
 System.out.println("LUGGAGE ALLOWANCE IS 80 Kg PER PERSON AND Rs.75 EXTRA PER Kg. OF LOAD. "); 
 System.out.println("VEG/NON-VEG MEAL IS AVAILABLE IN FLIGHT WITHOUT ANY EXTRA CHARGES."); 
 System.out.println("TV PER FLIER IS AVAILABLE WITH HEADPHONES(CAN BE CARRIED HOME) WITH FULL FLEDGE INCLINATION ENABLED SEATS");
System.out.println("SECURITY CHECK WILL CLOSE 15 MINUTES BEFORE TAKE OFF");
 System.out.println(); 
 System.out.println("Type 'c' to continue buying Jet Airways Air Tickets......"); 
 choice=br.readLine(); 
}
 while(choice.equalsIgnoreCase("c"));
}
}